package com.wemeal.presentation.util.events

/**
 * Custom Events
 *
 * Event names should be 40 characters or less, alphanumeric, and can include spaces, underscores or hyphens, but must not have a space or hyphen as the first character. Any given app should have no more than 1000 distinct event names.
 */
enum class CustomEvent(private var eventName: String, private var eventType: EventType, private var eventCase: EventCase? = null) : BaseEvent
{
    /*** CUSTOM EVENTS ***/

    // Launch App
    USER_LAUNCH_APP("USER_LAUNCH_APP", EventType.VIEW),

    //=======================================INTRO START==========================================
    // INTRO SCREEN 1 VIEW
    USER_VIEW_INTRO_SCREEN_1("USER_VIEW_INTRO_SCREEN_1", EventType.VIEW),

    // INTRO SCREEN 2 VIEW
    USER_VIEW_INTRO_SCREEN_2("USER_VIEW_INTRO_SCREEN_2", EventType.VIEW),

    // INTRO SCREEN 3 VIEW
    USER_VIEW_INTRO_SCREEN_3("USER_VIEW_INTRO_SCREEN_3", EventType.VIEW),

    // CONTINUE WITH FACEBOOK
    USER_CONTINUE_WITH_FACEBOOK("USER_CONTINUE_WITH_FACEBOOK", EventType.MUTATION),

    // FACEBOOK GET USER FRIENDS
    USER_FACEBOOK_GET_USER_FRIENDS("USER_FACEBOOK_GET_USER_FRIENDS", EventType.MUTATION),

    // FACEBOOK GET USER GENDER
    USER_FACEBOOK_GET_USER_GENDER("USER_FACEBOOK_GET_USER_GENDER", EventType.MUTATION),

    // CONTINUE WITH GOOGLE
    USER_CONTINUE_WITH_GOOGLE("USER_CONTINUE_WITH_GOOGLE", EventType.MUTATION),

    // GOOGLE GET USER CONTACTS
    USER_GOOGLE_GET_USER_CONTACTS("USER_GOOGLE_GET_USER_CONTACTS", EventType.MUTATION),
    //=======================================INTRO END==========================================

    //=================================== ON-BOARDING START ==========================================
    USER_ALLOW_LOCATION_ACCESS("USER_CLICK_ALLOW_LOCATION_ACCESS", EventType.VIEW),

    USER_SELECT_LOCATION_BY_MAP("USER_SELECT_LOCATION_BY_MAP", EventType.VIEW),

    USER_SEARCH_LOCATION_TYPING("USER_SEARCH_LOCATION_TYPING", EventType.VIEW),

    USER_SEARCH_LOCATION("USER_SEARCH_LOCATION", EventType.VIEW),

    USER_CLICK_CONFIRM_LOCATION("USER_CLICK_CONFIRM_LOCATION", EventType.MUTATION),

    USER_CLICK_CHANGE_LOCATION("USER_CLICK_CHANGE_LOCATION", EventType.VIEW),

    USER_SELECT_CURRENT_LOCATION("USER_SELECT_CURRENT_LOCATION", EventType.VIEW),

    USER_SELECT_CITY_FROM_LIST("USER_SELECT_CITY_FROM_LIST", EventType.VIEW),

    USER_SEARCH_CITY_FROM_LIST("USER_SEARCH_CITY_FROM_LIST", EventType.VIEW),

    USER_SELECT_AREA_FROM_LIST("USER_SELECT_AREA_FROM_LIST", EventType.VIEW),

    USER_SEARCH_AREA_FROM_LIST("USER_SEARCH_AREA_FROM_LIST", EventType.VIEW),

    USER_SELECT_SUBAREA_FROM_LIST("USER_SELECT_SUBAREA_FROM_LIST", EventType.VIEW),

    USER_SEARCH_SUBAREA_FROM_LIST("USER_SEARCH_SUBAREA_FROM_LIST", EventType.VIEW),

    USER_FOLLOW_RESTAURANT_FROM_CARD_ONBOARDING("USER_FOLLOW_RESTAURANT_FROM_CARD_ONBOARDING", EventType.MUTATION),

    USER_UNFOLLOW_RESTAURANT_FROM_CARD_ONBOARDING("USER_UNFOLLOW_RESTAURANT_FROM_CARD_ONBOARDING", EventType.MUTATION),

    USER_PROCEED_TO_FOLLOW_FOODIE_FROM_CARD_ONBOARDING("USER_PROCEED_TO_FOLLOW_FOODIE_FROM_CARD_ONBOARDING", EventType.VIEW),

    USER_PROCEED_TO_FEED_PAGE_FROM_ONBOARDING("USER_PROCEED_TO_FEED_PAGE_FROM_ONBOARDING", EventType.VIEW),

    USER_FOLLOW_FOODIE_FROM_CARD_ONBOARDING("USER_FOLLOW_FOODIE_FROM_CARD_ONBOARDING", EventType.MUTATION),

    USER_UNFOLLOW_FOODIE_FROM_CARD_ONBOARDING("USER_UNFOLLOW_FOODIE_FROM_CARD_ONBOARDING", EventType.MUTATION),
    //===================================ON-BOARDING END==========================================

    USER_LIKE_RESTAURANT_POST("USER_LIKE_RESTAURANT_POST", EventType.MUTATION),

    USER_LIKE_FOODIE_POST("USER_LIKE_FOODIE_POST", EventType.MUTATION),

    USER_LIKE_THEIR_POST("USER_LIKE_THEIR_POST", EventType.MUTATION),

    USER_UNLIKE_RESTAURANT_POST("USER_UNLIKE_RESTAURANT_POST", EventType.MUTATION),

    USER_UNLIKE_FOODIE_POST("USER_UNLIKE_FOODIE_POST", EventType.MUTATION),

    USER_UNLIKE_THEIR_POST("USER_UNLIKE_THEIR_POST", EventType.MUTATION),

    USER_CLICK_SHOW_MORE_POST("USER_CLICK_SHOW_MORE_POST", EventType.VIEW),

    USER_CLICK_SHOW_LESS_POST("USER_CLICK_SHOW_LESS_POST", EventType.VIEW),

    USER_CLICK_CAPTION_TO_VIEW_POST_DETAILS_PAGE("USER_CLICK_CAPTION_TO_VIEW_POST_DETAILS_PAGE", EventType.VIEW),

    USER_CLICK_IMAGE_TO_VIEW_POST_DETAILS_PAGE("USER_CLICK_IMAGE_TO_VIEW_POST_DETAILS_PAGE", EventType.VIEW),

    USER_CLICK_TIMESTAMP_TO_VIEW_POST_DETAILS_PAGE("USER_CLICK_TIMESTAMP_TO_VIEW_POST_DETAILS_PAGE", EventType.VIEW),

    USER_ESCAPE_POST_DETAILS_PAGE("USER_ESCAPE_POST_DETAILS_PAGE", EventType.VIEW),

    USER_CLICK_IMAGE_TO_VIEW_FULL_SCREEN("USER_CLICK_IMAGE_TO_VIEW_FULL_SCREEN", EventType.VIEW),

//    USER_SWIPE_IMAGES_ON_POST("USER_SWIPE_IMAGES_ON_POST", EventType.VIEW),
//
//    USER_ZOOM_IN_IMAGES_ON_POST("USER_ZOOM_IN_IMAGES_ON_POST", EventType.VIEW),
//
//    USER_ZOOM_OUT_IMAGES_ON_POST("USER_ZOOM_OUT_IMAGES_ON_POST", EventType.VIEW),
//
//    USER_CLICK_X_EXIT_SCREEN_FULL_MODE("USER_CLICK_X_EXIT_SCREEN_FULL_MODE", EventType.VIEW),

    USER_CLICK_MORE_ACTIONS_ON_POST("USER_CLICK_MORE_ACTIONS_ON_POST", EventType.VIEW),

    USER_COPY_POST_LINK("USER_COPY_POST_LINK", EventType.VIEW),

    USER_SHARE_POST_EXTERNALLY("USER_SHARE_POST_EXTERNALLY", EventType.VIEW),

    USER_CLICK_REPORT_POST("USER_CLICK_REPORT_POST", EventType.VIEW),

    USER_EXIT_REPORT_POST_SCREEN("USER_EXIT_REPORT_POST_SCREEN", EventType.VIEW),

    USER_SUBMIT_REPORT_POST("USER_SUBMIT_REPORT_POST", EventType.VIEW), //Cancel

    USER_CONFIRM_SUBMIT_REPORT_POST("USER_CONFIRM_SUBMIT_REPORT_POST", EventType.MUTATION),

    USER_CLICK_FOODIE_PROFILE_PICTURE_FROM_POST("USER_CLICK_FOODIE_PROFILE_PICTURE_FROM_POST", EventType.VIEW),

    USER_CLICK_FOODIE_NAME_FROM_POST("USER_CLICK_FOODIE_NAME_FROM_POST", EventType.VIEW),

    USER_UNFOLLOW_FOODIE_FROM_MORE_ACTIONS_ON_POST("USER_UNFOLLOW_FOODIE_FROM_MORE_ACTIONS_ON_POST", EventType.VIEW),

    USER_CLICK_RESTAURANT_LOGO_FROM_POST("USER_CLICK_RESTAURANT_LOGO_FROM_POST", EventType.VIEW),

    USER_CLICK_RESTAURANT_NAME_FROM_POST("USER_CLICK_RESTAURANT_NAME_FROM_POST", EventType.VIEW),

    USER_UNFOLLOW_RESTAURANT_FROM_MORE_ACTIONS("USER_UNFOLLOW_RESTAURANT_FROM_MORE_ACTIONS", EventType.VIEW),

    USER_CLICK_ON_THEIR_PROFILE_PICTURE("USER_CLICK_ON_THEIR_PROFILE_PICTURE", EventType.VIEW),

    USER_CLICK_ON_THEIR_NAME("USER_CLICK_ON_THEIR_NAME", EventType.VIEW),

    USER_CLICK_DELETE_POST("USER_CLICK_DELETE_POST", EventType.VIEW),

    USER_CONFIRM_DELETE_POST("USER_CONFIRM_DELETE_POST", EventType.VIEW),

    USER_CLICK_VIEW_MENU_FROM_RESTAURANT_TAGGED_POST("USER_CLICK_VIEW_MENU_FROM_RESTAURANT_TAGGED_POST", EventType.VIEW),

    USER_CLICK_VIEW_MEAL_FROM_MEAL_TAGGED_POST("USER_CLICK_VIEW_MEAL_FROM_MEAL_TAGGED_POST", EventType.VIEW),

    USER_CLICK_VIEW_OFFER_FROM_OFFER_TAGGED_POST("USER_CLICK_VIEW_OFFER_FROM_OFFER_TAGGED_POST", EventType.VIEW),

    USER_CLICK_VIEW_MENU_FROM_OFFER_TAGGED_POST("USER_CLICK_VIEW_MENU_FROM_OFFER_TAGGED_POST", EventType.VIEW),

    USER_CLICK_VIEW_ORDER_FROM_TAGGED_ORDER_POST("USER_CLICK_VIEW_ORDER_FROM_TAGGED_ORDER_POST", EventType.VIEW),

    USER_CLICK_RESTAURANT_LOGO_FROM_TAGGED_OBJECT("USER_CLICK_RESTAURANT_LOGO_FROM_TAGGED_OBJECT", EventType.VIEW),

    USER_CLICK_RESTAURANT_NAME_FROM_TAGGED_RESTAURANT("USER_CLICK_RESTAURANT_NAME_FROM_TAGGED_RESTAURANT", EventType.VIEW),

    USER_CLICK_ORDER_NAME_FROM_TAGGED_ORDER("USER_CLICK_ORDER_NAME_FROM_TAGGED_ORDER", EventType.VIEW),

    USER_CLICK_OFFER_NAME_FROM_TAGGED_OFFER("USER_CLICK_OFFER_NAME_FROM_TAGGED_OFFER", EventType.VIEW),

    USER_CLICK_MEAL_NAME_FROM_TAGGED_MEAL("USER_CLICK_MEAL_NAME_FROM_TAGGED_MEAL", EventType.VIEW),

    USER_CLICK_OFFER_ICON_FROM_TAGGED_OFFER("USER_CLICK_OFFER_ICON_FROM_TAGGED_OFFER", EventType.VIEW),

    USER_CLICK_MEAL_ICON_FROM_TAGGED_MEAL("USER_CLICK_MEAL_ICON_FROM_TAGGED_MEAL", EventType.VIEW),

    USER_CLICK_RESTAURANT_ICON_FROM_TAGGED_RESTAURANT("USER_CLICK_RESTAURANT_ICON_FROM_TAGGED_RESTAURANT", EventType.VIEW),

    //==============================================TYPE TWO=============================================================================
    USER_CLICK_FOODIE_NAME_FROM_ACTIVITY("USER_CLICK_FOODIE_NAME_FROM_ACTIVITY", EventType.VIEW),

    USER_CLICK_FOODIE_PROFILE_PICTURE_FROM_ACTIVITY("USER_CLICK_FOODIE_PROFILE_PICTURE_FROM_ACTIVITY", EventType.VIEW),

    USER_CLICK_RESTAURANT_LOGO_FROM_ACTIVITY("USER_CLICK_RESTAURANT_LOGO_FROM_ACTIVITY", EventType.VIEW),

    USER_CLICK_RESTAURANT_NAME_FROM_ACTIVITY("USER_CLICK_RESTAURANT_NAME_FROM_ACTIVITY", EventType.VIEW),

    USER_CLICK_VIEW_ORDER_FROM_ACTIVITY("USER_CLICK_VIEW_ORDER_FROM_ACTIVITY", EventType.VIEW),

    USER_CLICK_VIEW_MENU_FROM_RESTAURANT_CARD_FROM_ACTIVITY("USER_CLICK_VIEW_MENU_FROM_RESTAURANT_CARD_FROM_ACTIVITY", EventType.VIEW),

    USER_CLICK_VIEW_MENU_FROM_OFFER_CARD_FROM_ACTIVITY("USER_CLICK_VIEW_MENU_FROM_OFFER_CARD_FROM_ACTIVITY", EventType.VIEW),

    USER_CLICK_VIEW_OFFER_FROM_OFFER_CARD_FROM_ACTIVITY("USER_CLICK_VIEW_OFFER_FROM_OFFER_CARD_FROM_ACTIVITY", EventType.VIEW),

    USER_CLICK_VIEW_MEAL_FROM_MEAL_CARD_FROM_ACTIVITY("USER_CLICK_VIEW_MEAL_FROM_MEAL_CARD_FROM_ACTIVITY", EventType.VIEW),

    USER_CLICK_FOODIES_LIST_GROUP_FOLLOWING_FOODIE("USER_CLICK_FOODIES_LIST_GROUP_FOLLOWING_FOODIE", EventType.VIEW),

    USER_ESCAPE_CLICK_FOODIES_LIST_GROUP_FOLLOWING_FOODIE("USER_ESCAPE_CLICK_FOODIES_LIST_GROUP_FOLLOWING_FOODIE", EventType.VIEW),

    USER_SWIPE_FOLLOWED_FOODIES_CAROUSEL("USER_SWIPE_FOLLOWED_FOODIES_CAROUSEL", EventType.VIEW),

    USER_ESCAPE_SEE_ALL_FOLLOWED_FOODIES_LIST("USER_ESCAPE_SEE_ALL_FOLLOWED_FOODIES_LIST", EventType.VIEW),

    USER_FOLLOW_FOODIE_FROM_CARD("USER_FOLLOW_FOODIE_FROM_CARD", EventType.VIEW),

    USER_UNFOLLOW_FOODIE_FROM_CARD("USER_UNFOLLOW_FOODIE_FROM_CARD", EventType.VIEW),

    USER_FOLLOW_FOODIE_FROM_FOODIE_ACTIVITY_LIST("USER_FOLLOW_FOODIE_FROM_FOODIE_ACTIVITY_LIST", EventType.VIEW),

    USER_UNFOLLOW_FOODIE_FROM_FOODIE_ACTIVITY_LIST("USER_UNFOLLOW_FOODIE_FROM_FOODIE_ACTIVITY_LIST", EventType.VIEW),

    USER_CLICK_FOODIES_LIST_GROUP_FOLLOWING_RESTAURANT("USER_CLICK_FOODIES_LIST_GROUP_FOLLOWING_RESTAURANT", EventType.VIEW),

    USER_FOLLOW_RESTAURANT_FROM_CARD("USER_FOLLOW_RESTAURANT_FROM_CARD", EventType.VIEW),

    USER_ESCAPE_FOODIES_LIST_GROUP_FOLLOWING_RESTAURANT("USER_ESCAPE_FOODIES_LIST_GROUP_FOLLOWING_RESTAURANT", EventType.VIEW),

    USER_SWIPE_FOLLOWED_RESTAURANTS_CAROUSEL("USER_SWIPE_FOLLOWED_RESTAURANTS_CAROUSEL", EventType.VIEW),

    USER_CLICK_SEE_ALL_FOLLOWED_FOODIES_LIST("USER_CLICK_SEE_ALL_FOLLOWED_FOODIES_LIST", EventType.VIEW),

    USER_CLICK_SEE_ALL_FOLLOWED_RESTAURANTS_LIST("USER_CLICK_SEE_ALL_FOLLOWED_RESTAURANTS_LIST", EventType.VIEW),

    USER_ESCAPE_SEE_ALL_FOLLOWED_RESTAURANTS_LIST("USER_ESCAPE_SEE_ALL_FOLLOWED_RESTAURANTS_LIST", EventType.VIEW),

    USER_UNFOLLOW_RESTAURANT_FROM_CARD("USER_UNFOLLOW_RESTAURANT_FROM_CARD", EventType.VIEW),

    USER_CLICK_FOODIES_LIST_GROUP_ORDERING_ACTIVITY("USER_CLICK_FOODIES_LIST_GROUP_ORDERING_ACTIVITY", EventType.VIEW),

    USER_ESCAPE_FOODIES_LIST_GROUP_ORDERING_ACTIVITY("USER_ESCAPE_FOODIES_LIST_GROUP_ORDERING_ACTIVITY", EventType.VIEW),

    USER_CLICK_FOODIES_LIST_GROUP_COMMENTING_ACTIVITY("USER_CLICK_FOODIES_LIST_GROUP_COMMENTING_ACTIVITY", EventType.VIEW),

    USER_ESCAPE_FOODIES_LIST_GROUP_COMMENTING_ACTIVITY("USER_ESCAPE_FOODIES_LIST_GROUP_COMMENTING_ACTIVITY", EventType.VIEW),

    USER_ESCAPE_FOODIES_LIST_GROUP_SHARING_ACTIVITY("USER_ESCAPE_FOODIES_LIST_GROUP_SHARING_ACTIVITY", EventType.VIEW),

    USER_CLICK_FOODIES_LIST_GROUP_SHARING_ACTIVITY("USER_CLICK_FOODIES_LIST_GROUP_SHARING_ACTIVITY", EventType.VIEW),

    USER_CLICK_FOODIES_LIST_GROUP_POSTING_ACTIVITY("USER_CLICK_FOODIES_LIST_GROUP_POSTING_ACTIVITY", EventType.VIEW),

    USER_ESCAPE_FOODIES_LIST_GROUP_POSTING_ACTIVITY("USER_ESCAPE_FOODIES_LIST_GROUP_POSTING_ACTIVITY", EventType.VIEW),

    //CREATE-POST
    USER_CLICK_CREATE_POST_ACTION_BOX("USER_CLICK_CREATE_POST_ACTION_BOX", EventType.VIEW),

    USER_EXCEED_CHARACTER_LIMIT_CREATE_POST("USER_EXCEED_CHARACTER_LIMIT_CREATE_POST", EventType.VIEW),

    USER_CLICK_TRY_AGAIN_CREATE_POST("USER_CLICK_TRY_AGAIN_CREATE_POST", EventType.MUTATION),

    USER_MENTION_FOODIE_IN_POST("USER_MENTION_FOODIE_IN_POST", EventType.MUTATION),

    USER_CLICK_POST("USER_CLICK_POST", EventType.MUTATION),

    USER_DISCARD_CREATE_POST("USER_DISCARD_CREATE_POST", EventType.VIEW),

    USER_CONFIRM_DISCARD_POST("USER_CONFIRM_DISCARD_POST", EventType.VIEW),

    USER_DISCARD_POST_CANCEL("USER_DISCARD_POST_CANCEL", EventType.VIEW),

    USER_CLICK_ADD_IMAGES_CREATE_POST("USER_CLICK_ADD_IMAGES_CREATE_POST", EventType.VIEW),

    USER_CLICK_CONFIRM_SELECTED_IMAGES_CREATE_POST("USER_CLICK_CONFIRM_SELECTED_IMAGES_CREATE_POST", EventType.VIEW),

    USER_REMOVE_IMAGE_SINGLE_IMAGE_SELECTED_CREATE_POST("USER_REMOVE_IMAGE_SINGLE_IMAGE_SELECTED_CREATE_POST", EventType.VIEW),

    USER_EDIT_IMAGE_SELECTION_CREATE_POST("USER_EDIT_IMAGE_SELECTION_CREATE_POST", EventType.VIEW),

    USER_CLICK_TAG_RESTAURANT_MEAL_OFFER_ORDER_CREATE_POST("USER_CLICK_TAG_RESTAURANT_MEAL_OFFER_ORDER_CREATE_POST", EventType.VIEW),

    //TAGGED RESTAURANT
    USER_CLICK_RESTAURANTS_TAB_TAGGING_RESTAURANT_CREATE_POST("USER_CLICK_RESTAURANTS_TAB_TAGGING_RESTAURANT_CREATE_POST", EventType.VIEW),

    USER_SEARCH_TAGGING_RESTAURANT_CREATE_POST("USER_SEARCH_TAGGING_RESTAURANT_CREATE_POST", EventType.VIEW),

    USER_CONFIRM_SEARCH_TAGGING_RESTAURANT_CREATE_POST("USER_CONFIRM_SEARCH_TAGGING_RESTAURANT_CREATE_POST", EventType.VIEW),

    USER_REMOVE_TAGGED_RESTAURANT_CREATE_POST("USER_REMOVE_TAGGED_RESTAURANT_CREATE_POST", EventType.VIEW),

    USER_SELECT_TAGGED_RESTAURANT_CREATE_POST("USER_SELECT_TAGGED_RESTAURANT_CREATE_POST", EventType.VIEW),

    USER_REMOVE_SEARCH_QUERY_TAGGING_RESTAURANT("USER_REMOVE_SEARCH_QUERY_TAGGING_RESTAURANT", EventType.VIEW),

    //TAGGED MEAL
    USER_CLICK_MEALS_TAB_TAGGING_MEAL_CREATE_POST("USER_CLICK_MEALS_TAB_TAGGING_MEAL_CREATE_POST", EventType.VIEW),

    USER_SEARCH_TAGGED_MEAL_CREATE_POST("USER_SEARCH_TAGGED_MEAL_CREATE_POST", EventType.VIEW),

    USER_CONFIRM_SEARCH_TAGGING_MEAL_CREATE_POST("USER_CONFIRM_SEARCH_TAGGING_MEAL_CREATE_POST", EventType.VIEW),

    USER_SELECT_TAGGED_MEAL_CREATE_POST("USER_SELECT_TAGGED_MEAL_CREATE_POST", EventType.VIEW),

    USER_REMOVE_TAGGED_MEAL_CREATE_POST("USER_REMOVE_TAGGED_MEAL_CREATE_POST", EventType.VIEW),

    USER_REMOVE_SEARCH_QUERY_TAGGING_MEAL("USER_REMOVE_SEARCH_QUERY_TAGGING_MEAL", EventType.VIEW),

    //TAGGED OFFER
    USER_CLICKS_OFFERS_TAB_TAGGING_OFFER_CREATE_POST("USER_CLICKS_OFFERS_TAB_TAGGING_OFFER_CREATE_POST", EventType.VIEW),

    USER_SEARCH_TAGGED_OFFER_CREATE_POST("USER_SEARCH_TAGGED_OFFER_CREATE_POST", EventType.VIEW),

    USER_CONFIRM_SEARCH_TAGGING_OFFER_CREATE_POST("USER_CONFIRM_SEARCH_TAGGING_OFFER_CREATE_POST", EventType.VIEW),

    USER_SELECT_TAGGED_OFFER_CREATE_POST("USER_SELECT_TAGGED_OFFER_CREATE_POST", EventType.VIEW),

    USER_REMOVE_TAGGED_OFFER_CREATE_POST("USER_REMOVE_TAGGED_OFFER_CREATE_POST", EventType.VIEW),

    USER_REMOVE_SEARCH_QUERY_TAGGING_OFFER("USER_REMOVE_SEARCH_QUERY_TAGGING_OFFER", EventType.VIEW),

    //TAGGED ORDER
    USER_CLICKS_ORDERS_TAB_TAGGING_MEAL_CREATE_POST("USER_CLICKS_ORDERS_TAB_TAGGING_MEAL_CREATE_POST", EventType.VIEW),

    USER_SEARCH_TAGGED_ORDER_CREATE_POST("USER_SEARCH_TAGGED_ORDER_CREATE_POST", EventType.VIEW),

    USER_CONFIRM_SEARCH_TAGGING_ORDER_CREATE_POST("USER_CONFIRM_SEARCH_TAGGING_ORDER_CREATE_POST", EventType.VIEW),

    USER_SELECT_TAGGED_ORDER_CREATE_POST("USER_SELECT_TAGGED_ORDER_CREATE_POST", EventType.VIEW),

    USER_REMOVE_TAGGED_ORDER_CREATE_POST("USER_REMOVE_TAGGED_ORDER_CREATE_POST", EventType.VIEW),

    USER_REMOVE_SEARCH_QUERY_TAGGING_ORDER("USER_REMOVE_SEARCH_QUERY_TAGGING_ORDER", EventType.VIEW),

    USER_CLICK_ADD_IMAGES_FROM_ADDING_IMAGE_PROMPT_SCREEN_TAGGING_OBJECT("USER_CLICK_ADD_IMAGES_FROM_ADDING_IMAGE_PROMPT_SCREEN_TAGGING_OBJECT", EventType.VIEW),

    USER_CLICK_ADD_IMAGES_FROM_ADDING_IMAGE_PROMPT_POPUP_TAGGING_OBJECT("USER_CLICK_ADD_IMAGES_FROM_ADDING_IMAGE_PROMPT_POPUP_TAGGING_OBJECT", EventType.VIEW),

    USER_CLICK_POST_ANYWAY_ADDING_IMAGE_PROMPT_POPUP_TAGGING_OBJECT("USER_CLICK_POST_ANYWAY_ADDING_IMAGE_PROMPT_POPUP_TAGGING_OBJECT", EventType.VIEW),

    USER_CLICK_CHOOSE_FROM_RESTAURANT_GALLERY_ADDING_IMAGE_PROMPT_SCREEN_TAGGING_OBJECT("USER_CLICK_CHOOSE_FROM_RESTAURANT_GALLERY_ADDING_IMAGE_PROMPT_SCREEN_TAGGING_OBJECT", EventType.VIEW),

    USER_SELECT_IMAGE_FROM_RESTAURANT_GALLERY("USER_SELECT_IMAGE_FROM_RESTAURANT_GALLERY", EventType.VIEW),

    USER_CLICK_ADD_FROM_RESTAURANT_GALLERY("USER_CLICK_ADD_FROM_RESTAURANT_GALLERY", EventType.VIEW),

    USER_ESCAPE_RESTAURANT_GALLERY("USER_ESCAPE_RESTAURANT_GALLERY", EventType.VIEW),

    USER_CLICK_ALSO_SHARE_ON_RESTAURANT_PAGE_CREATE_POST("USER_CLICK_ALSO_SHARE_ON_RESTAURANT_PAGE_CREATE_POST", EventType.VIEW),

    USER_CLICK_EDIT_ON_POST("USER_CLICK_EDIT_ON_POST", EventType.VIEW),

    USER_CLICK_X_ESCAPING_COMMUNITY_RULES_POSTING_TIP("USER_CLICK_X_ESCAPING_COMMUNITY_RULES_POSTING_TIP", EventType.VIEW),

    USER_CLICK_X_ESCAPING_TAGGING_OBJECT_POSTING_TIP("USER_CLICK_X_ESCAPING_TAGGING_OBJECT_POSTING_TIP", EventType.VIEW),

    USER_CLICK_RULES_DURING_CREATING_POST("USER_CLICK_RULES_DURING_CREATING_POST", EventType.VIEW),

    USER_CLICK_AGREE_COMMUNITY_RULES("USER_CLICK_AGREE_COMMUNITY_RULES", EventType.VIEW),

    USER_CLICK_OUTSIDE_OVERLAY_ESCAPING_COMMUNITY_RULES("USER_CLICK_OUTSIDE_OVERLAY_ESCAPING_COMMUNITY_RULES", EventType.VIEW),

    USER_CLICK_X_ESCAPING_COMMUNITY_RULES("USER_CLICK_X_ESCAPING_COMMUNITY_RULES", EventType.VIEW),

    USER_EXIT_COMMUNITY_RULES_CREATING_POST("USER_EXIT_COMMUNITY_RULES_CREATING_POST", EventType.VIEW),

    USER_CLICK_X_CLOSE_POST_MODEREATED_FEEDBACK("USER_CLICK_X_CLOSE_POST_MODEREATED_FEEDBACK", EventType.VIEW),

    USER_CLICK_CREATE_NEW_POST_FROM_POST_MODERATED_FEEDBACK("USER_CLICK_CREATE_NEW_POST_FROM_POST_MODERATED_FEEDBACK", EventType.VIEW),

    USER_CLICK_COMMUNITY_RULES_FROM_POST_MODERATED_FEEDBACK("USER_CLICK_COMMUNITY_RULES_FROM_POST_MODERATED_FEEDBACK", EventType.VIEW);

    /*** OVERRIDE FUNCTIONS ***/

    override fun getEventName(): String
    {

        if (eventCase == null)
        {
            throw Error("eventCase cannot be null when getting the eventFullName")
        }

        return eventName + "_" + eventCase
    }

    override fun getEventCase(): EventCase?
    {
        return eventCase
    }

    override fun setEventCase(eventCase: EventCase)
    {
        this.eventCase = eventCase
    }

    override fun getEventType(): EventType?
    {
        return eventType
    }

    override fun hasStandardParams(): Boolean
    {
        return false
    }

    override fun hasValueToSum(): Boolean
    {
        return false
    }
}
